import Foundation

struct BreedConstants {
    static let allBreeds: [Breed] = [
        Breed(
            id: "alambadi",
            name: "Alambadi",
            description: "A draught breed of Tamil Nadu, known for its endurance and strength in heavy field work.",
            region: "Dharmapuri and Erode districts, Tamil Nadu",
            milkProduction: "Low (2-3 liters/day)",
            climateSuitability: "Hot and dry tropical",
            pros: ["Sturdy", "High endurance", "Low maintenance"],
            cons: ["Low milk yield", "Slow growth"],
            farmingSuitability: "Heavy draught work",
            temperament: "Active and energetic",
            lifespan: "15-18 years",
            diseaseResistance: "Excellent against local parasites",
            useCases: ["Ploughing", "Cart pulling", "Organic farming"],
            imageURL: "alambadi"
        ),
        Breed(
            id: "amritmahal",
            name: "Amritmahal",
            description: "Known for its speed and endurance, this breed was historically used for military transport in Mysore.",
            region: "Karnataka",
            milkProduction: "Very Low",
            climateSuitability: "Hot and semi-arid",
            pros: ["Extremely fast", "Exceptional endurance", "Highly intelligent"],
            cons: ["Low milk production", "Spirited temperament"],
            farmingSuitability: "Speed draught and transport",
            temperament: "Fiery and alert",
            lifespan: "18-20 years",
            diseaseResistance: "Very High",
            useCases: ["Draught", "Heritage conservation"],
            imageURL: "amritmahal"
        ),
        Breed(
            id: "ayrshire",
            name: "Ayrshire",
            description: "A stylish dairy breed originating from Scotland, known for its longevity and hardiness compared to other exotic breeds.",
            region: "Global (Adapted to hilly regions in India)",
            milkProduction: "High (20-25 liters/day)",
            climateSuitability: "Cool to temperate",
            pros: ["High milk quality", "Easy calving", "Excellent foragers"],
            cons: ["Prone to heat stress", "Requires high-quality nutrition"],
            farmingSuitability: "Commercial dairy",
            temperament: "Active",
            lifespan: "12-15 years",
            diseaseResistance: "Moderate",
            useCases: ["Milk", "Cheese production"],
            imageURL: "ayrshire"
        ),
        Breed(
            id: "banni",
            name: "Banni",
            description: "Also known as Kutch Buffalo, this breed is famous for night grazing and high milk fat content.",
            region: "Kutch region, Gujarat",
            milkProduction: "High (12-15 liters/day)",
            climateSuitability: "Arid and saline regions",
            pros: ["High fat milk", "Drought resistant", "Unique night grazing habit"],
            cons: ["Requires large grazing area", "Aggressive"],
            farmingSuitability: "Desert dairy farming",
            temperament: "Wild and hardy",
            lifespan: "18-20 years",
            diseaseResistance: "High",
            useCases: ["Milk", "Ghee production"],
            imageURL: "banni"
        ),
        Breed(
            id: "bargur",
            name: "Bargur",
            description: "A hill cattle breed known for its ability to navigate mountainous terrain with ease.",
            region: "Bargur hills, Tamil Nadu",
            milkProduction: "Low (1-2 liters/day)",
            climateSuitability: "Hill climate",
            pros: ["Mountain navigation", "Extremely hardy", "Low feed requirement"],
            cons: ["Low yield", "Small size"],
            farmingSuitability: "Hill agriculture",
            temperament: "Alert and active",
            lifespan: "14-16 years",
            diseaseResistance: "Very High",
            useCases: ["Hill draught", "Milk for home use"],
            imageURL: "bargur"
        ),
        Breed(
            id: "bhadawari",
            name: "Bhadawari",
            description: "A prominent buffalo breed known for having the highest fat content in milk among all breeds.",
            region: "Uttar Pradesh and Madhya Pradesh",
            milkProduction: "Moderate (4-6 liters/day)",
            climateSuitability: "Hot and humid",
            pros: ["Highest milk fat (up to 13%)", "Efficient feed conversion", "Heat tolerant"],
            cons: ["Lower milk volume", "Slow maturity"],
            farmingSuitability: "High-fat dairy production",
            temperament: "Quiet and gentle",
            lifespan: "16-18 years",
            diseaseResistance: "Excellent",
            useCases: ["Ghee production", "Milk"],
            imageURL: "bhadawari"
        ),
        Breed(
            id: "brown_swiss",
            name: "Brown Swiss",
            description: "One of the oldest dairy breeds, known for its large size and high protein milk.",
            region: "Global (Used in cross-breeding in India)",
            milkProduction: "Very High (25-30 liters/day)",
            climateSuitability: "Temperate",
            pros: ["High protein milk", "Strong legs", "Docile"],
            cons: ["High maintenance", "Heat sensitive"],
            farmingSuitability: "Industrial dairy",
            temperament: "Very calm",
            lifespan: "12-14 years",
            diseaseResistance: "Average",
            useCases: ["Milk", "Cheese", "Cross-breeding"],
            imageURL: "brown_swiss"
        ),
        Breed(
            id: "dangi",
            name: "Dangi",
            description: "Known for its distinctive white coat with black spots, it is highly resistant to heavy rainfall.",
            region: "Nashik and Ahmednagar, Maharashtra",
            milkProduction: "Low",
            climateSuitability: "Heavy rainfall areas",
            pros: ["Water resistant skin", "Hardy hooves", "Docile"],
            cons: ["Low milk yield", "Slow walker"],
            farmingSuitability: "Rice field cultivation",
            temperament: "Placid",
            lifespan: "15-18 years",
            diseaseResistance: "High",
            useCases: ["Paddy field work", "Draught"],
            imageURL: "dangi"
        ),
        Breed(
            id: "deoni",
            name: "Deoni",
            description: "A dual-purpose breed famous for its striking black and white spotted appearance and heavy build.",
            region: "Latur and Bidar districts",
            milkProduction: "Moderate (5-8 liters/day)",
            climateSuitability: "Semi-arid",
            pros: ["Dual purpose", "Stately appearance", "Good milk yield"],
            cons: ["Slow growth", "Requires grooming"],
            farmingSuitability: "Integrated farming",
            temperament: "Gentle",
            lifespan: "16-18 years",
            diseaseResistance: "Excellent",
            useCases: ["Milk", "Draught", "Exhibition"],
            imageURL: "deoni"
        ),
        Breed(
            id: "gir",
            name: "Gir",
            description: "World-famous dairy breed known for its prominent forehead and convex face.",
            region: "Gujarat",
            milkProduction: "High (12-15 liters/day)",
            climateSuitability: "Tropical",
            pros: ["Very high yield", "Heat resistant", "Disease resistant"],
            cons: ["Requires quality fodder"],
            farmingSuitability: "Dairy farming",
            temperament: "Very calm",
            lifespan: "15-18 years",
            diseaseResistance: "Very High",
            useCases: ["A2 Milk", "Breeding"],
            imageURL: "gir"
        ),
        Breed(
            id: "guernsey",
            name: "Guernsey",
            description: "Known for producing 'Golden Milk' due to high beta-carotene content.",
            region: "Global",
            milkProduction: "High (20-22 liters/day)",
            climateSuitability: "Temperate",
            pros: ["Golden milk", "High fat/protein", "Docile"],
            cons: ["Small frame", "Heat sensitive"],
            farmingSuitability: "Premium dairy",
            temperament: "Gentle",
            lifespan: "12-15 years",
            diseaseResistance: "Average",
            useCases: ["Milk", "Butter"],
            imageURL: "guernsey"
        ),
        Breed(
            id: "hallikar",
            name: "Hallikar",
            description: "The primary draught breed of Karnataka, used for its immense strength and speed.",
            region: "South Karnataka",
            milkProduction: "Low",
            climateSuitability: "Dry tropical",
            pros: ["Strongest draught breed", "Fast paced", "Stamina"],
            cons: ["Low milk", "Aggressive if provoked"],
            farmingSuitability: "Intensive draught",
            temperament: "Spirited",
            lifespan: "18-20 years",
            diseaseResistance: "High",
            useCases: ["Transport", "Ploughing"],
            imageURL: "hallikar"
        ),
        Breed(
            id: "hariana",
            name: "Hariana",
            description: "A prominent dual-purpose breed from North India, white/light grey in color.",
            region: "Haryana, Punjab, UP",
            milkProduction: "Moderate (5-10 liters/day)",
            climateSuitability: "Hot and dry",
            pros: ["Excellent draught bulls", "Good milk yield", "Hardy"],
            cons: ["Large size", "Average yield"],
            farmingSuitability: "Mixed farming",
            temperament: "Active",
            lifespan: "15-17 years",
            diseaseResistance: "Good",
            useCases: ["Milk", "Agriculture"],
            imageURL: "hariana"
        ),
        Breed(
            id: "holstein_friesian",
            name: "Holstein Friesian",
            description: "The highest producing dairy breed in the world, distinct black and white markings.",
            region: "Global",
            milkProduction: "Very High (30-40 liters/day)",
            climateSuitability: "Cool temperate",
            pros: ["Maximum yield", "Fast growth", "Adaptable"],
            cons: ["Very high maintenance", "Zero heat tolerance"],
            farmingSuitability: "Industrial dairy",
            temperament: "Calm",
            lifespan: "10-12 years",
            diseaseResistance: "Low",
            useCases: ["Industrial Milk"],
            imageURL: "holstein_friesian"
        ),
        Breed(
            id: "jaffrabadi",
            name: "Jaffrabadi",
            description: "The heaviest buffalo breed, known for its massive horns and high fat milk.",
            region: "Saurashtra, Gujarat",
            milkProduction: "High (10-12 liters/day)",
            climateSuitability: "Hot and humid",
            pros: ["Massive size", "High fat", "Long lactation"],
            cons: ["Large feed intake", "Slow maturity"],
            farmingSuitability: "Commercial dairy",
            temperament: "Quiet",
            lifespan: "18-20 years",
            diseaseResistance: "High",
            useCases: ["Milk", "Butter"],
            imageURL: "jaffrabadi"
        ),
        Breed(
            id: "jersey",
            name: "Jersey",
            description: "Small dairy breed producing rich, creamy milk with high fat content.",
            region: "Global",
            milkProduction: "High (18-22 liters/day)",
            climateSuitability: "Adaptable",
            pros: ["High fat milk", "Early maturity", "Small size"],
            cons: ["Heat sensitive", "Fragile"],
            farmingSuitability: "Efficient dairy",
            temperament: "Nervous",
            lifespan: "12-15 years",
            diseaseResistance: "Average",
            useCases: ["Milk", "Cream"],
            imageURL: "jersey"
        ),
        Breed(
            id: "kangayam",
            name: "Kangayam",
            description: "A world-class draught breed from Tamil Nadu, known for its majestic appearance.",
            region: "Kangayam region, TN",
            milkProduction: "Low",
            climateSuitability: "Hot and arid",
            pros: ["Unmatched endurance", "Beautiful horns", "Hardy hooves"],
            cons: ["Poor milker"],
            farmingSuitability: "Professional draught",
            temperament: "Aggressive",
            lifespan: "20+ years",
            diseaseResistance: "Extreme",
            useCases: ["Heavy transport", "Stud", "Jallikattu"],
            imageURL: "kangayam"
        ),
        Breed(
            id: "kankrej",
            name: "Kankrej",
            description: "One of the heaviest Indian cattle, famous for its unique 'Sawai Chal' (walking style).",
            region: "Banaskantha, Gujarat",
            milkProduction: "Moderate (8-10 liters/day)",
            climateSuitability: "Arid",
            pros: ["Fastest walker", "Powerful draught", "Good milk"],
            cons: ["Needs large space"],
            farmingSuitability: "Semi-arid dairy",
            temperament: "Intelligent",
            lifespan: "18-20 years",
            diseaseResistance: "High",
            useCases: ["Milk", "Draught"],
            imageURL: "kankrej"
        ),
        Breed(
            id: "kasargod",
            name: "Kasargod",
            description: "A dwarf cattle breed from Kerala, known for its tiny stature and extreme hardiness.",
            region: "Kerala",
            milkProduction: "Very Low",
            climateSuitability: "High humidity",
            pros: ["Miniature size", "Zero maintenance", "Highly resistant"],
            cons: ["Low yield"],
            farmingSuitability: "Home gardens",
            temperament: "Docile",
            lifespan: "15-20 years",
            diseaseResistance: "Extreme",
            useCases: ["Zero-budget farming", "Pet"],
            imageURL: "kasargod"
        ),
        Breed(
            id: "kenkatha",
            name: "Kenkatha",
            description: "A small, sturdy draught breed from the Bundelkhand region.",
            region: "UP and MP border",
            milkProduction: "Low",
            climateSuitability: "Semi-arid",
            pros: ["Thrives on poor feed", "Hardy", "Agile"],
            cons: ["Small size", "Low milk"],
            farmingSuitability: "Smallholder farming",
            temperament: "Active",
            lifespan: "15-18 years",
            diseaseResistance: "High",
            useCases: ["Light draught", "Ploughing"],
            imageURL: "kenkatha"
        ),
        Breed(
            id: "kherigarh",
            name: "Kherigarh",
            description: "Known for its white coat and thin, small horns. Active and suited for light work.",
            region: "Kheri district, UP",
            milkProduction: "Very Low",
            climateSuitability: "Humid sub-tropical",
            pros: ["Very active", "Fast walker", "Low feed"],
            cons: ["Negligible milk"],
            farmingSuitability: "Light cart work",
            temperament: "Nervous",
            lifespan: "14-16 years",
            diseaseResistance: "Good",
            useCases: ["Draught"],
            imageURL: "kherigarh"
        ),
        Breed(
            id: "khillari",
            name: "Khillari",
            description: "A premier draught breed of Maharashtra, known for its strength and aggressive power.",
            region: "Western Maharashtra",
            milkProduction: "Very Low",
            climateSuitability: "Dry tropical",
            pros: ["Immense strength", "Fast draught", "Stamina"],
            cons: ["Aggressive", "Low milk"],
            farmingSuitability: "Commercial transport",
            temperament: "Fierce",
            lifespan: "18-20 years",
            diseaseResistance: "High",
            useCases: ["Bullock carts", "Heavy ploughing"],
            imageURL: "khillari"
        ),
        Breed(
            id: "krishna_valley",
            name: "Krishna Valley",
            description: "A heavy dual-purpose breed found in the Krishna river valley.",
            region: "Karnataka border area",
            milkProduction: "Moderate (3-5 liters/day)",
            climateSuitability: "Riverine areas",
            pros: ["Heavy draught", "Large size", "Powerful"],
            cons: ["Slow maturity", "High feed requirement"],
            farmingSuitability: "Black cotton soil ploughing",
            temperament: "Calm",
            lifespan: "16-18 years",
            diseaseResistance: "Good",
            useCases: ["Heavy agriculture", "Milk"],
            imageURL: "krishna_valley"
        ),
        Breed(
            id: "malnad_gidda",
            name: "Malnad Gidda",
            description: "A dwarf cattle breed of Karnataka, perfectly adapted to heavy rains and forests.",
            region: "Malnad, Karnataka",
            milkProduction: "Low (2-3 liters/day)",
            climateSuitability: "Rainforest",
            pros: ["Small size", "Medicinal milk", "Forest foraging"],
            cons: ["Low volume"],
            farmingSuitability: "Organic hill farming",
            temperament: "Alert",
            lifespan: "15-20 years",
            diseaseResistance: "Extreme",
            useCases: ["High fat milk", "Dung for manure"],
            imageURL: "malnad_gidda"
        ),
        Breed(
            id: "mehsana",
            name: "Mehsana",
            description: "A cross between Murrah and Surti buffaloes, offering high yield and fat.",
            region: "Mehsana, Gujarat",
            milkProduction: "High (12-18 liters/day)",
            climateSuitability: "Dry and hot",
            pros: ["Consistent yield", "Early calving", "Good fat"],
            cons: ["Requires management"],
            farmingSuitability: "Commercial dairy",
            temperament: "Docile",
            lifespan: "18-20 years",
            diseaseResistance: "High",
            useCases: ["Milk", "Butter"],
            imageURL: "mehsana"
        ),
        Breed(
            id: "murrah",
            name: "Murrah",
            description: "The 'Black Gold' of India. Most famous dairy buffalo breed in the world.",
            region: "Haryana and Punjab",
            milkProduction: "Very High (15-25 liters/day)",
            climateSuitability: "Varied",
            pros: ["Highest yield", "Jet black color", "Curled horns"],
            cons: ["High feed requirement"],
            farmingSuitability: "Top-tier dairy",
            temperament: "Gentle",
            lifespan: "18-22 years",
            diseaseResistance: "Excellent",
            useCases: ["Primary milk source", "Breeding"],
            imageURL: "murrah"
        ),
        Breed(
            id: "nagori",
            name: "Nagori",
            description: "Renowned as one of the best trotting (fast walking) draught breeds of India.",
            region: "Nagaur, Rajasthan",
            milkProduction: "Low",
            climateSuitability: "Desert",
            pros: ["Extremely fast trotter", "Hardy hooves", "Stamina"],
            cons: ["Negligible milk"],
            farmingSuitability: "Fast transport",
            temperament: "Alert",
            lifespan: "18-20 years",
            diseaseResistance: "High",
            useCases: ["Cart racing", "Fast transport"],
            imageURL: "nagori"
        ),
        Breed(
            id: "nagpuri",
            name: "Nagpuri",
            description: "A versatile buffalo breed with long, flat horns, suited for central India.",
            region: "Nagpur and Berar, MH",
            milkProduction: "Moderate (4-6 liters/day)",
            climateSuitability: "Hot and dry",
            pros: ["Heat tolerant", "Dual purpose", "Sturdy"],
            cons: ["Lower yield than Murrah"],
            farmingSuitability: "Mixed farming",
            temperament: "Quiet",
            lifespan: "16-18 years",
            diseaseResistance: "High",
            useCases: ["Milk", "Draught"],
            imageURL: "nagpuri"
        ),
        Breed(
            id: "nili_ravi",
            name: "Nili Ravi",
            description: "Known as the 'Panj-Kalyani' due to five white markings on its body.",
            region: "Ferozepur, Punjab",
            milkProduction: "High (15-18 liters/day)",
            climateSuitability: "Riverine",
            pros: ["High yield", "Docile", "Good fat"],
            cons: ["Requires water/wallowing"],
            farmingSuitability: "Commercial dairy",
            temperament: "Placid",
            lifespan: "18-20 years",
            diseaseResistance: "Good",
            useCases: ["Milk", "Ghee"],
            imageURL: "nili_ravi"
        ),
        Breed(
            id: "nimari",
            name: "Nimari",
            description: "A draught breed of Madhya Pradesh, known for its copper-red coat with white spots.",
            region: "Nimar region, MP",
            milkProduction: "Low",
            climateSuitability: "Hot and humid",
            pros: ["Sturdy draught", "Attractive color", "Heat tolerant"],
            cons: ["Low milk"],
            farmingSuitability: "Field work",
            temperament: "Active",
            lifespan: "15-17 years",
            diseaseResistance: "High",
            useCases: ["Draught"],
            imageURL: "nimari"
        ),
        Breed(
            id: "ongole",
            name: "Ongole",
            description: "World-famous breed known for its massive size and resistance to Mad Cow disease.",
            region: "Andhra Pradesh",
            milkProduction: "Moderate (4-6 liters/day)",
            climateSuitability: "Tropical",
            pros: ["Huge draught power", "Disease resistant", "Heat tolerant"],
            cons: ["High maintenance due to size"],
            farmingSuitability: "Heavy draught and milk",
            temperament: "Docile",
            lifespan: "18-22 years",
            diseaseResistance: "Extreme",
            useCases: ["Heavy draught", "Milk", "Stud"],
            imageURL: "ongole"
        ),
        Breed(
            id: "pulikulam",
            name: "Pulikulam",
            description: "A specialized draught breed used primarily for Jallikattu and traditional farming.",
            region: "Madurai, Tamil Nadu",
            milkProduction: "Very Low",
            climateSuitability: "Dry tropical",
            pros: ["Extremely agile", "Low feed", "Brave"],
            cons: ["Low milk", "Aggressive"],
            farmingSuitability: "Traditional farming",
            temperament: "Fierce",
            lifespan: "15-20 years",
            diseaseResistance: "High",
            useCases: ["Jallikattu", "Security", "Draught"],
            imageURL: "pulikulam"
        ),
        Breed(
            id: "rathi",
            name: "Rathi",
            description: "An important dual-purpose breed of Rajasthan, brown with white patches.",
            region: "Bikaner and Ganganagar",
            milkProduction: "Moderate to High (10-12 liters/day)",
            climateSuitability: "Desert",
            pros: ["Good milker", "Thrives in desert", "Low maintenance"],
            cons: ["Slow maturity"],
            farmingSuitability: "Desert dairy",
            temperament: "Gentle",
            lifespan: "15-18 years",
            diseaseResistance: "High",
            useCases: ["Milk", "Draught"],
            imageURL: "rathi"
        ),
        Breed(
            id: "red_dane",
            name: "Red Dane",
            description: "A Danish dairy breed introduced for cross-breeding and high milk production.",
            region: "Global (Crosses found in India)",
            milkProduction: "Very High (25-30 liters/day)",
            climateSuitability: "Cooler climates",
            pros: ["Excellent yield", "Good growth", "High fat"],
            cons: ["Heat sensitive", "High feed cost"],
            farmingSuitability: "Commercial dairy",
            temperament: "Active",
            lifespan: "12-14 years",
            diseaseResistance: "Average",
            useCases: ["Milk", "Beef (in West)"],
            imageURL: "red_dane"
        ),
        Breed(
            id: "red_sindhi",
            name: "Red Sindhi",
            description: "A hardy red breed capable of adapting to various climates, good milk producer.",
            region: "Varied (Sindh origin)",
            milkProduction: "High (10-12 liters/day)",
            climateSuitability: "Adaptable",
            pros: ["Hardy", "Consistent yield", "Disease resistant"],
            cons: ["Average draught"],
            farmingSuitability: "Dairy farming",
            temperament: "Nervous but docile with handling",
            lifespan: "15-18 years",
            diseaseResistance: "High",
            useCases: ["Milk", "Cross-breeding"],
            imageURL: "red_sindhi"
        ),
        Breed(
            id: "sahiwal",
            name: "Sahiwal",
            description: "Arguably the best indigenous dairy breed in India, known for sweet milk.",
            region: "North India",
            milkProduction: "Very High (15-20 liters/day)",
            climateSuitability: "Hot and dry",
            pros: ["Highest yield among Desi breeds", "High fat", "Lethargic"],
            cons: ["Prone to mastitis"],
            farmingSuitability: "Intensive dairy",
            temperament: "Docile",
            lifespan: "16-18 years",
            diseaseResistance: "Good",
            useCases: ["Primary milk", "Breeding"],
            imageURL: "sahiwal"
        ),
        Breed(
            id: "surti",
            name: "Surti",
            description: "A medium-sized buffalo breed known for its sickle-shaped horns.",
            region: "Charotar, Gujarat",
            milkProduction: "Moderate (5-8 liters/day)",
            climateSuitability: "Hot and humid",
            pros: ["Small size", "Easy to maintain", "High fat"],
            cons: ["Lower yield than Murrah"],
            farmingSuitability: "Small-scale dairy",
            temperament: "Gentle",
            lifespan: "16-18 years",
            diseaseResistance: "Excellent",
            useCases: ["Milk", "Ghee"],
            imageURL: "surti"
        ),
        Breed(
            id: "tharparkar",
            name: "Tharparkar",
            description: "The 'White Sindhi', famous for its drought resistance and dual-purpose utility.",
            region: "Rajasthan",
            milkProduction: "Moderate (8-10 liters/day)",
            climateSuitability: "Arid/Desert",
            pros: ["Drought resistant", "Good draught bulls", "Hardy"],
            cons: ["Lower yield than Sahiwal"],
            farmingSuitability: "Desert integrated farming",
            temperament: "Calm",
            lifespan: "18-20 years",
            diseaseResistance: "Very High",
            useCases: ["Milk", "Draught"],
            imageURL: "tharparkar"
        ),
        Breed(
            id: "toda",
            name: "Toda",
            description: "A semi-wild buffalo breed of the Nilgiri hills, sacred to the Toda people.",
            region: "Nilgiris, Tamil Nadu",
            milkProduction: "Low (3-5 liters/day)",
            climateSuitability: "Hilly and cold",
            pros: ["Cold resistant", "Forest foraging", "Unique appearance"],
            cons: ["Semi-wild", "Aggressive"],
            farmingSuitability: "Hill pastoralism",
            temperament: "Fierce",
            lifespan: "15-18 years",
            diseaseResistance: "High",
            useCases: ["Religious rituals", "Milk"],
            imageURL: "toda"
        ),
        Breed(
            id: "umblachery",
            name: "Umblachery",
            description: "Known as the 'Jathi Madu', a small draught breed of Tamil Nadu with white patches.",
            region: "Nagapattinam, TN",
            milkProduction: "Low",
            climateSuitability: "Hot and humid",
            pros: ["Small and sturdy", "Excellent for paddy fields", "Low feed"],
            cons: ["Low milk"],
            farmingSuitability: "Wetland draught",
            temperament: "Active",
            lifespan: "15-18 years",
            diseaseResistance: "High",
            useCases: ["Ploughing", "Cart pulling"],
            imageURL: "umblachery"
        ),
        Breed(
            id: "vechur",
            name: "Vechur",
            description: "The smallest cattle breed in the world, famous for medicinal milk and tiny size.",
            region: "Kerala",
            milkProduction: "Low (2-3 liters/day)",
            climateSuitability: "Tropical",
            pros: ["World's smallest", "Medicinal milk", "Zero-maintenance"],
            cons: ["Low volume"],
            farmingSuitability: "Backyard farming",
            temperament: "Extremely docile",
            lifespan: "15-20 years",
            diseaseResistance: "Extreme",
            useCases: ["Medicinal milk", "Pet"],
            imageURL: "vechur"
        )
    ]
}
